# Generated by Django 6.0.6 on 2026-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='📚', max_length=50)),
                ('background_theme', models.CharField(choices=[('QURAN', 'Quran'), ('MEMORY', 'Memory'), ('SOROBAN', 'Soroban'), ('PROBLEM_SOLVING', 'Problem Solving'), ('HEALTH', 'Health'), ('HISTORY', 'History'), ('LANGUAGES', 'Languages'), ('TALENTS', 'Talents'), ('PSYCHOLOGY', 'Psychology')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('color_primary', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_sessions', models.BooleanField(default=True)),
                ('show_pdfs', models.BooleanField(default=True)),
                ('show_videos', models.BooleanField(default=True)),
                ('show_voice', models.BooleanField(default=True)),
                ('show_photos', models.BooleanField(default=True)),
                ('show_quizzes', models.BooleanField(default=True)),
                ('show_schedule', models.BooleanField(default=True)),
            ],
        ),
    ]
