# Generated by Django 6.0.6 on 2026-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_payment_created_by_payment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
