# Generated by Django 6.0.6 on 2026-07-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='benefits',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='module',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/'),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_outcomes',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
