# Generated by Django 6.0.6 on 2026-08-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_module_benefits_module_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.AlterField(
            model_name='module',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='heroes/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('EDAHABIA', 'Edahabia')], default='CASH', max_length=20),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
