# Generated by Django 6.0.6 on 2026-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('landing_hero_title', models.CharField(default='أكاديمية فتنة للتطوير المستمر', max_length=255)),
                ('landing_hero_subtitle', models.TextField(blank=True, default='انضم إلينا وابدأ رحلة التعلم')),
                ('landing_primary_button_text', models.CharField(default='سجل الآن', max_length=50)),
                ('landing_primary_button_url', models.CharField(default='/login', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
