# Generated by Django 6.0.6 on 2026-07-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_desc',
            field=models.TextField(blank=True, default='نُعدّهم للحياة، لا للامتحانات!'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='جميع الحقوق محفوظة © منصة فطنة', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='global_font_family',
            field=models.CharField(default='Cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_about_us',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_features_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_stats_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_testimonials_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_tiktok',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_whatsapp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_hero_subtitle',
            field=models.TextField(blank=True, default='نُعدّهم للحياة، لا للامتحانات!'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_hero_title',
            field=models.CharField(default='منصة فطنة', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_primary_button_text',
            field=models.CharField(default='ابدأ رحلتك الآن 🚀', max_length=50),
        ),
    ]
