# Generated by Django 6.0.6 on 2026-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_footer_desc_sitesettings_footer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='global_font_family',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='landing_about_us',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='landing_primary_button_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='landing_primary_button_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_about_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_about_title',
            field=models.CharField(blank=True, default='من نحن؟', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_cta_button_text',
            field=models.CharField(default='سجل الآن', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_cta_button_url',
            field=models.CharField(default='/login', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_cta_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_cta_title',
            field=models.CharField(blank=True, default='جاهز للبدء؟', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_faq_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_hero_button_text',
            field=models.CharField(default='ابدأ رحلتك الآن 🚀', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_hero_button_url',
            field=models.CharField(default='/login', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_programs_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
