# Generated by Django 6.0.6 on 2026-07-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesettings_global_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, default='منصة فطنة', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_primary_color',
            field=models.CharField(blank=True, default='#F5C518', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_secondary_color',
            field=models.CharField(blank=True, default='#7C3AED', max_length=7),
        ),
    ]
