# Generated by Django 6.0.6 on 2026-07-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_logo_sitesettings_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='landing_faq_title',
            field=models.CharField(blank=True, default='الأسئلة الشائعة', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_features_subtitle',
            field=models.TextField(blank=True, default='تجربة تعليمية تفاعلية مليئة بالألعاب والتحديات والمكافآت لتحفزك كل يوم على التقدم والتعلم.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_features_title',
            field=models.CharField(blank=True, default='التعلم أصبح أكثر متعة!', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_how_it_works_title',
            field=models.CharField(blank=True, default='كيف تعمل المنصة؟', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_programs_title',
            field=models.CharField(blank=True, default='برامجنا الممتعة ✨', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_stats_title',
            field=models.CharField(blank=True, default='إنجازاتنا بالأرقام', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_testimonials_title',
            field=models.CharField(blank=True, default='ماذا يقولون عنا؟', max_length=255),
        ),
    ]
