# Generated by Django 6.0.6 on 2026-08-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_landing_faq_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, default='الجزائر العاصمة'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.CharField(blank=True, default='info@fitna.dz', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+213773650836', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_desc',
            field=models.TextField(blank=True, default='منصة تعليمية تربوية تهدف لتأسيس أطفالنا وتطوير مهاراتهم باللعب والتفاعل.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_about_text',
            field=models.TextField(blank=True, default='نرى اليوم واقعاً مؤلماً؛ أطفال صغار تائهون بين شاشات الهواتف. من هذا الألم، وُلدت فكرة منصة فطنة لتقديم بديل آمن وتربوي ممتع.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_cta_button_text',
            field=models.CharField(blank=True, default='ابدأ الآن', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_cta_button_url',
            field=models.CharField(blank=True, default='/login', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_cta_text',
            field=models.TextField(blank=True, default='انضم إلى آلاف الطلاب واستمتع بتجربة تعليمية فريدة.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_cta_title',
            field=models.CharField(blank=True, default='جاهز تصنع إنجازك؟', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_faq_json',
            field=models.TextField(blank=True, default='[\n  {"q": "كيف يمكن تسجيل ابني في المنصة؟", "a": "يمكنك الضغط على زر ابدأ الآن واختيار البرنامج المناسب وإدخال معلومات الطالب."},\n  {"q": "هل المحتوى مناسب لجميع الأعمار؟", "a": "نعم، البرامج مخصصة للأطفال والناشئة من سن 9 إلى 18 سنة بمستويات تدرجية."},\n  {"q": "هل تقدم المنصة شهادات إتمام؟", "a": "نعم، يحصل الطالب على شهادة إتمام معتمدة فور إكمال كافة متطلبات البرنامج التعليمي."}\n]'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_features_json',
            field=models.TextField(blank=True, default='[\n  {"title": "تحديات يومية", "desc": "أكمل التحديات اليومية واربح نقاط ومكافآت رائعة.", "icon": "🎯"},\n  {"title": "نظام الأوسمة", "desc": "احصل على أوسمة تميز عند إتمام كل وحدة تعليمية.", "icon": "👑"},\n  {"title": "لوحة الصدارة", "desc": "تنافس مع أصدقائك وتصدر قائمة المبدعين الأسبوعية.", "icon": "🏆"},\n  {"title": "شهادات معتمدة", "desc": "احصل على شهادات إنجاز موثقة عند إتمام أي برنامج.", "icon": "📜"}\n]'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_hero_button_text',
            field=models.CharField(blank=True, default='ابدأ الآن', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_hero_button_url',
            field=models.CharField(blank=True, default='/login', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_hero_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_hero_title',
            field=models.CharField(blank=True, default='منصة فطنة', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_how_it_works_title',
            field=models.CharField(blank=True, default='كيف يعمل الموقع؟', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_programs_json',
            field=models.TextField(blank=True, default='[\n  {"slug": "quran", "name": "قسم التعليم القرآني", "description": "حفظ وتجويد بطرق تفاعلية مبتكرة لترسيخ القرآن في النفوس.", "icon": "🕌"},\n  {"slug": "memory", "name": "الذاكرة الخارقة", "description": "تطوير مهارات الحفظ السريع والاستيعاب الفائق.", "icon": "🧠"},\n  {"slug": "soroban", "name": "الحساب الذهني (السوروبان)", "description": "تطوير سرعة الحساب والدقة في حل المسائل المالية والرياضية.", "icon": "🧮"},\n  {"slug": "problem-solving", "name": "حل المشكلات والمنطق", "description": "تنمية التفكير النقدي والتحليلي لدى الأطفال.", "icon": "🧩"}\n]'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_stats_json',
            field=models.TextField(blank=True, default='[\n  {"num": 1250, "label": "طالب مبدع", "emoji": "👨\u200d🎓"},\n  {"num": 8, "label": "برامج متخصصة", "emoji": "📚"},\n  {"num": 98, "label": "نسبة الرضا", "emoji": "⭐"},\n  {"num": 15, "label": "مشرف معتمد", "emoji": "🏆"}\n]'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landing_testimonials_json',
            field=models.TextField(blank=True, default='[\n  {"name": "أحمد بن علي", "role": "ولي أمر طالب", "text": "منصة فطنة غيّرت حياة ابني تماماً، أصبح يقضي وقته في حفظ القرآن والحساب الذهني بدلاً من الألعاب الإلكترونية."},\n  {"name": "مريم البتول", "role": "أم لطالبة", "text": "المحتوى التفاعلي ممتاز جداً والتنافسية محفزة. ابنتي أصبحت أكثر ثقة بنفسها وبشكل ملحوظ."},\n  {"name": "ياسين المحمدي", "role": "ولي أمر", "text": "بيئة آمنة ومحتوى هادف، شكراً لفريق منصة فطنة على هذا العمل العظيم."}\n]'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, default='منصة فطنة', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_password_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_facebook',
            field=models.CharField(blank=True, default='https://facebook.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_instagram',
            field=models.CharField(blank=True, default='https://instagram.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_tiktok',
            field=models.CharField(blank=True, default='https://tiktok.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_whatsapp',
            field=models.CharField(blank=True, default='+213773650836', max_length=255),
        ),
    ]
