# Generated by Django 6.0.6 on 2026-07-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=70),
        ),
    ]
