# Generated by Django 6.0.6 on 2026-07-20 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_lesson_is_preview'),
        ('quizzes', '0003_alter_quiz_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.lesson'),
        ),
    ]
