# Generated by Django 6.0.6 on 2026-08-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
    ]
