# Generated by Django 6.0.6 on 2026-08-09 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_video_video_file_remove_video_video_url_and_more'),
        ('quizzes', '0005_remove_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='content.lesson'),
        ),
    ]
