# Generated by Django 6.0.6 on 2026-07-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='modules.module'),
        ),
        migrations.AddField(
            model_name='photo',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='modules.module'),
        ),
        migrations.AddField(
            model_name='session',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='modules.module'),
        ),
        migrations.AddField(
            model_name='video',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='modules.module'),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_messages', to='modules.module'),
        ),
    ]
