# Generated by Django 6.0.6 on 2026-07-18 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('modules', '0005_alter_module_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='module',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='module',
        ),
        migrations.RemoveField(
            model_name='session',
            name='module',
        ),
        migrations.RemoveField(
            model_name='video',
            name='module',
        ),
        migrations.RemoveField(
            model_name='voicemessage',
            name='module',
        ),
        migrations.AddField(
            model_name='document',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='photo',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='session',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_messages', to='content.lesson'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='modules.module')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.section'),
        ),
    ]
