# Generated by Django 6.0.6 on 2026-07-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_document_document_file_photo_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
