# Generated by Django 6.0.6 on 2026-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_lesson_is_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='رابط فيديو تيليغرام', null=True),
        ),
    ]
